// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using GGtk = Gtk;


namespace Optimization.Runner.Gtk
{
	internal partial class MainWindow {
	    
	    private GGtk.VBox vbox1;
	    
	    private GGtk.Table table1;
	    
	    private GGtk.Label label_best;
	    
	    private GGtk.Label label_job;
	    
	    private GGtk.Label label_last_update;
	    
	    private GGtk.Label label_started;
	    
	    private GGtk.Label label1;
	    
	    private GGtk.Label label3;
	    
	    private GGtk.Label label4;
	    
	    private GGtk.Label label5;
	    
	    private GGtk.HSeparator hseparator1;
	    
	    private GGtk.Expander expander_details;
	    
	    private GGtk.ScrolledWindow scrolled_window_details;
	    
	    private GGtk.TextView text_view_details;
	    
	    private GGtk.Label GtkLabel;
	    
	    private GGtk.HBox hbox1;
	    
	    private GGtk.ProgressBar progressbar_progress;
	    
	    private GGtk.Button button_stop;
	    
	    protected virtual void Build() {
	        Stetic.Gui.Initialize(this);
	        // Widget MainWindow
	        this.Name = "MainWindow";
	        this.Title = Mono.Unix.Catalog.GetString("Optimization");
	        this.WindowPosition = ((GGtk.WindowPosition)(4));
	        this.BorderWidth = ((uint)(10));
	        this.DefaultHeight = 50;
	        // Container child MainWindow.GGtk.Container+ContainerChild
	        this.vbox1 = new GGtk.VBox();
	        this.vbox1.Name = "vbox1";
	        this.vbox1.Spacing = 6;
	        // Container child vbox1.GGtk.Box+BoxChild
	        this.table1 = new GGtk.Table(((uint)(4)), ((uint)(2)), false);
	        this.table1.Name = "table1";
	        this.table1.RowSpacing = ((uint)(3));
	        this.table1.ColumnSpacing = ((uint)(3));
	        // Container child table1.GGtk.Table+TableChild
	        this.label_best = new GGtk.Label();
	        this.label_best.Name = "label_best";
	        this.label_best.Xalign = 0F;
	        this.table1.Add(this.label_best);
	        GGtk.Table.TableChild w1 = ((GGtk.Table.TableChild)(this.table1[this.label_best]));
	        w1.TopAttach = ((uint)(3));
	        w1.BottomAttach = ((uint)(4));
	        w1.LeftAttach = ((uint)(1));
	        w1.RightAttach = ((uint)(2));
	        w1.XOptions = ((GGtk.AttachOptions)(4));
	        w1.YOptions = ((GGtk.AttachOptions)(4));
	        // Container child table1.GGtk.Table+TableChild
	        this.label_job = new GGtk.Label();
	        this.label_job.Name = "label_job";
	        this.label_job.Xalign = 0F;
	        this.table1.Add(this.label_job);
	        GGtk.Table.TableChild w2 = ((GGtk.Table.TableChild)(this.table1[this.label_job]));
	        w2.LeftAttach = ((uint)(1));
	        w2.RightAttach = ((uint)(2));
	        w2.YOptions = ((GGtk.AttachOptions)(4));
	        // Container child table1.GGtk.Table+TableChild
	        this.label_last_update = new GGtk.Label();
	        this.label_last_update.Name = "label_last_update";
	        this.label_last_update.Xalign = 0F;
	        this.table1.Add(this.label_last_update);
	        GGtk.Table.TableChild w3 = ((GGtk.Table.TableChild)(this.table1[this.label_last_update]));
	        w3.TopAttach = ((uint)(2));
	        w3.BottomAttach = ((uint)(3));
	        w3.LeftAttach = ((uint)(1));
	        w3.RightAttach = ((uint)(2));
	        w3.XOptions = ((GGtk.AttachOptions)(4));
	        w3.YOptions = ((GGtk.AttachOptions)(4));
	        // Container child table1.GGtk.Table+TableChild
	        this.label_started = new GGtk.Label();
	        this.label_started.Name = "label_started";
	        this.label_started.Xalign = 0F;
	        this.table1.Add(this.label_started);
	        GGtk.Table.TableChild w4 = ((GGtk.Table.TableChild)(this.table1[this.label_started]));
	        w4.TopAttach = ((uint)(1));
	        w4.BottomAttach = ((uint)(2));
	        w4.LeftAttach = ((uint)(1));
	        w4.RightAttach = ((uint)(2));
	        w4.XOptions = ((GGtk.AttachOptions)(4));
	        w4.YOptions = ((GGtk.AttachOptions)(4));
	        // Container child table1.GGtk.Table+TableChild
	        this.label1 = new GGtk.Label();
	        this.label1.Name = "label1";
	        this.label1.Xalign = 0F;
	        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Best:");
	        this.table1.Add(this.label1);
	        GGtk.Table.TableChild w5 = ((GGtk.Table.TableChild)(this.table1[this.label1]));
	        w5.TopAttach = ((uint)(3));
	        w5.BottomAttach = ((uint)(4));
	        w5.XOptions = ((GGtk.AttachOptions)(4));
	        w5.YOptions = ((GGtk.AttachOptions)(4));
	        // Container child table1.GGtk.Table+TableChild
	        this.label3 = new GGtk.Label();
	        this.label3.Name = "label3";
	        this.label3.Xalign = 0F;
	        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Started:");
	        this.table1.Add(this.label3);
	        GGtk.Table.TableChild w6 = ((GGtk.Table.TableChild)(this.table1[this.label3]));
	        w6.TopAttach = ((uint)(1));
	        w6.BottomAttach = ((uint)(2));
	        w6.XOptions = ((GGtk.AttachOptions)(4));
	        w6.YOptions = ((GGtk.AttachOptions)(4));
	        // Container child table1.GGtk.Table+TableChild
	        this.label4 = new GGtk.Label();
	        this.label4.Name = "label4";
	        this.label4.Xalign = 0F;
	        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Last update:");
	        this.table1.Add(this.label4);
	        GGtk.Table.TableChild w7 = ((GGtk.Table.TableChild)(this.table1[this.label4]));
	        w7.TopAttach = ((uint)(2));
	        w7.BottomAttach = ((uint)(3));
	        w7.XOptions = ((GGtk.AttachOptions)(4));
	        w7.YOptions = ((GGtk.AttachOptions)(4));
	        // Container child table1.GGtk.Table+TableChild
	        this.label5 = new GGtk.Label();
	        this.label5.Name = "label5";
	        this.label5.Xalign = 0F;
	        this.label5.LabelProp = Mono.Unix.Catalog.GetString("Job:");
	        this.table1.Add(this.label5);
	        GGtk.Table.TableChild w8 = ((GGtk.Table.TableChild)(this.table1[this.label5]));
	        w8.XOptions = ((GGtk.AttachOptions)(4));
	        w8.YOptions = ((GGtk.AttachOptions)(4));
	        this.vbox1.Add(this.table1);
	        GGtk.Box.BoxChild w9 = ((GGtk.Box.BoxChild)(this.vbox1[this.table1]));
	        w9.Position = 0;
	        w9.Expand = false;
	        w9.Fill = false;
	        // Container child vbox1.GGtk.Box+BoxChild
	        this.hseparator1 = new GGtk.HSeparator();
	        this.hseparator1.Name = "hseparator1";
	        this.vbox1.Add(this.hseparator1);
	        GGtk.Box.BoxChild w10 = ((GGtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
	        w10.Position = 1;
	        w10.Expand = false;
	        w10.Fill = false;
	        // Container child vbox1.GGtk.Box+BoxChild
	        this.expander_details = new GGtk.Expander(null);
	        this.expander_details.CanFocus = true;
	        this.expander_details.Name = "expander_details";
	        // Container child expander_details.GGtk.Container+ContainerChild
	        this.scrolled_window_details = new GGtk.ScrolledWindow();
	        this.scrolled_window_details.CanFocus = true;
	        this.scrolled_window_details.Name = "scrolled_window_details";
	        this.scrolled_window_details.ShadowType = ((GGtk.ShadowType)(1));
	        // Container child scrolled_window_details.GGtk.Container+ContainerChild
	        this.text_view_details = new GGtk.TextView();
	        this.text_view_details.HeightRequest = 50;
	        this.text_view_details.CanFocus = true;
	        this.text_view_details.Name = "text_view_details";
	        this.text_view_details.WrapMode = ((GGtk.WrapMode)(3));
	        this.scrolled_window_details.Add(this.text_view_details);
	        this.expander_details.Add(this.scrolled_window_details);
	        this.GtkLabel = new GGtk.Label();
	        this.GtkLabel.Name = "GtkLabel";
	        this.GtkLabel.LabelProp = Mono.Unix.Catalog.GetString("Details");
	        this.GtkLabel.UseUnderline = true;
	        this.expander_details.LabelWidget = this.GtkLabel;
	        this.vbox1.Add(this.expander_details);
	        GGtk.Box.BoxChild w13 = ((GGtk.Box.BoxChild)(this.vbox1[this.expander_details]));
	        w13.Position = 2;
	        // Container child vbox1.GGtk.Box+BoxChild
	        this.hbox1 = new GGtk.HBox();
	        this.hbox1.Name = "hbox1";
	        this.hbox1.Spacing = 6;
	        // Container child hbox1.GGtk.Box+BoxChild
	        this.progressbar_progress = new GGtk.ProgressBar();
	        this.progressbar_progress.Name = "progressbar_progress";
	        this.progressbar_progress.Text = Mono.Unix.Catalog.GetString("0/0");
	        this.hbox1.Add(this.progressbar_progress);
	        GGtk.Box.BoxChild w14 = ((GGtk.Box.BoxChild)(this.hbox1[this.progressbar_progress]));
	        w14.Position = 0;
	        // Container child hbox1.GGtk.Box+BoxChild
	        this.button_stop = new GGtk.Button();
	        this.button_stop.CanFocus = true;
	        this.button_stop.Name = "button_stop";
	        this.button_stop.UseStock = true;
	        this.button_stop.UseUnderline = true;
	        this.button_stop.Label = "gtk-stop";
	        this.hbox1.Add(this.button_stop);
	        GGtk.Box.BoxChild w15 = ((GGtk.Box.BoxChild)(this.hbox1[this.button_stop]));
	        w15.Position = 1;
	        w15.Expand = false;
	        w15.Fill = false;
	        this.vbox1.Add(this.hbox1);
	        GGtk.Box.BoxChild w16 = ((GGtk.Box.BoxChild)(this.vbox1[this.hbox1]));
	        w16.Position = 3;
	        w16.Expand = false;
	        w16.Fill = false;
	        this.Add(this.vbox1);
	        if ((this.Child != null)) {
	            this.Child.ShowAll();
	        }
	        this.DefaultWidth = 400;
	        this.Show();
	    }
	}
}